name: Generate pacman animation

on:
  schedule:
    - cron: "0 */12 * * *" # Roda a cada 12h
  workflow_dispatch:       # Permite rodar manualmente
  push:
    branches:
      - main               # Roda quando fizer push na main

jobs:
  generate:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Generate pacman graph SVG
        uses: abozanona/pacman-contribution-graph@main
        with:
          github_user_name: Wsfrog

      - name: List files to debug
        run: ls -la

      - name: Publish to output branch (root dir)
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: . # Publica tudo da raiz (sem precisar mover o SVG)
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
